//! Emits slugcxl_4x4_top.sv — instantiates the endpoint + the attached
//! Gemma wrapper (systolic_array_4x4). This is the module Verilator targets.

use crate::config::CxlEndpointConfig;

pub fn emit(cfg: &CxlEndpointConfig) -> String {
    let name = &cfg.name;
    let wrapper = &cfg.attached_wrapper.module;
    let token_w = cfg.attached_wrapper.token_width;

    format!(
        r#"// Generated by slugcxl-gen. Do not edit.
// Top wrapper for {name}: slugcxl_endpoint + {wrapper}.

module slugcxl_4x4_top #(
  parameter integer FLIT_BITS = 512,
  parameter integer TOKEN_WIDTH = {token_w}
) (
  input  wire                     clk,
  input  wire                     rst_n,

  // Host-facing FLIT ports.
  input  wire                     flit_in_valid,
  output wire                     flit_in_ready,
  input  wire [FLIT_BITS-1:0]     flit_in_data,

  output wire                     flit_out_valid,
  input  wire                     flit_out_ready,
  output wire [FLIT_BITS-1:0]     flit_out_data
);

  // Internal wires between endpoint and wrapper.
  wire                     w_cmd_valid;
  wire                     w_cmd_ready;
  wire [TOKEN_WIDTH-1:0]   w_token_in;
  wire                     w_done_valid;
  wire [TOKEN_WIDTH-1:0]   w_token_out;

  slugcxl_endpoint #(
    .TOKEN_WIDTH(TOKEN_WIDTH),
    .FLIT_BITS(FLIT_BITS)
  ) u_endpoint (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_valid(flit_in_valid),
    .flit_in_ready(flit_in_ready),
    .flit_in_data(flit_in_data),
    .flit_out_valid(flit_out_valid),
    .flit_out_ready(flit_out_ready),
    .flit_out_data(flit_out_data),
    .cmd_valid(w_cmd_valid),
    .cmd_ready(w_cmd_ready),
    .token_in(w_token_in),
    .done_valid(w_done_valid),
    .token_out(w_token_out)
  );

  {wrapper} #(
    .TOKEN_WIDTH(TOKEN_WIDTH)
  ) u_wrapper (
    .clk(clk),
    .rst_n(rst_n),
    .cmd_valid(w_cmd_valid),
    .cmd_ready(w_cmd_ready),
    .token_in(w_token_in),
    .done_valid(w_done_valid),
    .token_out(w_token_out)
  );

endmodule
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snapshot_top_sv() {
        let cfg = CxlEndpointConfig::slugcxl_4x4();
        let sv = emit(&cfg);
        insta::assert_snapshot!(sv);
    }
}
