//! Emits Quartus project scaffolding for the generated HJ top.

use crate::config::CxlEndpointConfig;

pub fn emit_qpf() -> String {
    r#"PROJECT_REVISION = "slugcxl_hj_agilex"
"#
    .to_string()
}

pub fn emit_qsf(_cfg: &CxlEndpointConfig) -> String {
    r#"# Generated by slugcxl-gen. Edit board-specific pins/part before tape-out builds.
set_global_assignment -name FAMILY "Agilex 7"
set_global_assignment -name TOP_LEVEL_ENTITY slugcxl_4x4_hj_top
set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files
set_global_assignment -name SYSTEMVERILOG_FILE generated/slugcxl_hj_pipeline.sv
set_global_assignment -name SYSTEMVERILOG_FILE generated/slugcxl_4x4_hj_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE generated/slugcxl_endpoint.sv
set_global_assignment -name SYSTEMVERILOG_FILE generated/slugcxl_4x4_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../../vendor/gemma-generated/generated/systolic_array_16x16/rtl/systolic_array_16x16_df_wrapper.sv
set_global_assignment -name VERILOG_FILE ../../vendor/gemma-generated/rtl/designs/sovryn_pan_stem_systolic_array_16x16_baseline.v
set_global_assignment -name SDC_FILE quartus/slugcxl_hj_agilex.sdc
"#
    .to_string()
}

pub fn emit_sdc() -> String {
    r#"# Generated timing constraints. Replace with board-specific clocks for final builds.
create_clock -name clk -period 2.500 [get_ports clk]
"#
    .to_string()
}

pub fn emit_build_tcl() -> String {
    r#"# Generated by slugcxl-gen.
set project slugcxl_hj_agilex
project_open $project

if {![info exists env(SLUGCXL_AGILEX_DEVICE)]} {
  error "Set SLUGCXL_AGILEX_DEVICE to the exact Quartus device part, e.g. for your Agilex R-Tile board."
}

set_global_assignment -name DEVICE $env(SLUGCXL_AGILEX_DEVICE)
execute_flow -compile
project_close
"#
    .to_string()
}

pub fn emit_build_script() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v quartus_sh >/dev/null 2>&1; then
  echo "quartus_sh not found. Install Quartus Prime Pro or set PATH." >&2
  exit 127
fi

if [[ -z "${SLUGCXL_AGILEX_DEVICE:-}" ]]; then
  echo "Set SLUGCXL_AGILEX_DEVICE to the exact Quartus device part for your board." >&2
  exit 2
fi

quartus_sh -t quartus/build_slugcxl_hj_sof.tcl
sof="output_files/slugcxl_hj_agilex.sof"
if [[ ! -f "$sof" ]]; then
  echo "Quartus completed but $sof was not produced" >&2
  exit 1
fi
echo "$sof"
"#
    .to_string()
}
