//! Emits the hardware-JIT replay pipeline.

use crate::config::{CxlEndpointConfig, HardwareJitConfig};

pub fn emit(_cfg: &CxlEndpointConfig, hj: &HardwareJitConfig) -> String {
    let record_mode = hj.record_mode_code();
    let sample_stride = hj.sample_stride;
    let fifo_depth = hj.metadata_fifo_depth;
    let record_bytes = hj.metadata_record_bytes;

    format!(
        r#"// Generated by slugcxl-gen. Do not edit.
// Hardware-JIT replay pipeline for the SlugCXL endpoint.
// This block is endpoint-local EMC logic: it classifies CXL FLITs,
// assigns epochs, hashes/captures payload metadata, and exposes counters.

module slugcxl_hj_pipeline #(
  parameter integer FLIT_BITS             = 512,
  parameter integer RECORD_MODE           = {record_mode},  // 0 validation, 1 delta, 2 full
  parameter integer SAMPLE_STRIDE         = {sample_stride},
  parameter integer METADATA_FIFO_DEPTH   = {fifo_depth},
  parameter integer METADATA_RECORD_BYTES = {record_bytes}
) (
  input  wire                 clk,
  input  wire                 rst_n,

  // Host -> hardware-JIT -> endpoint.
  input  wire                 h2d_flit_valid,
  output wire                 h2d_flit_ready,
  input  wire [FLIT_BITS-1:0] h2d_flit_data,

  output wire                 ep_flit_valid,
  input  wire                 ep_flit_ready,
  output wire [FLIT_BITS-1:0] ep_flit_data,

  // Endpoint -> hardware-JIT -> host.
  input  wire                 ep_resp_valid,
  output wire                 ep_resp_ready,
  input  wire [FLIT_BITS-1:0] ep_resp_data,

  output wire                 d2h_flit_valid,
  input  wire                 d2h_flit_ready,
  output wire [FLIT_BITS-1:0] d2h_flit_data,

  // Compact replay-record stream. In the v1 generator this is a monitor
  // stream; if metadata_ready is low, the data path still runs and
  // metadata_drop_count increments.
  output wire                 metadata_valid,
  input  wire                 metadata_ready,
  output wire [255:0]         metadata_data,

  output reg  [63:0]          record_count,
  output reg  [63:0]          metadata_bytes,
  output reg  [63:0]          app_flit_bytes,
  output reg  [63:0]          stall_cycles,
  output reg  [63:0]          metadata_drop_count
);

  // Pass-through datapath. The HJ pipeline is observational unless a
  // later policy chooses to enforce provenance or stall epochs.
  assign ep_flit_valid  = h2d_flit_valid;
  assign h2d_flit_ready = ep_flit_ready;
  assign ep_flit_data   = h2d_flit_data;

  assign d2h_flit_valid = ep_resp_valid;
  assign ep_resp_ready  = d2h_flit_ready;
  assign d2h_flit_data  = ep_resp_data;

  wire h2d_fire = h2d_flit_valid && h2d_flit_ready;
  wire d2h_fire = d2h_flit_valid && d2h_flit_ready;
  wire any_fire = h2d_fire || d2h_fire;
  wire choose_h2d = h2d_fire;
  wire [FLIT_BITS-1:0] chosen_flit = choose_h2d ? h2d_flit_data : ep_resp_data;

  wire [3:0]  chosen_class  = chosen_flit[7:4];
  wire [3:0]  chosen_opcode = chosen_flit[3:0];
  wire [15:0] chosen_tag    = chosen_flit[23:8];
  wire [63:0] chosen_addr   = chosen_flit[87:24];
  wire [31:0] chosen_token  = chosen_flit[119:88];

  reg [63:0] epoch_id;
  reg [31:0] sample_ctr;

  wire sampled = any_fire && (sample_ctr == 32'd0);
  assign metadata_valid = sampled;

  wire [63:0] payload_hash = hash_payload(chosen_flit);
  wire [15:0] payload_capture_bytes = capture_bytes(chosen_flit);

  assign metadata_data = {{
    32'h53484a54,        // "SHJT"
    payload_hash,
    epoch_id,
    chosen_addr,
    chosen_tag,
    chosen_class,
    chosen_opcode,
    4'd0,
    (choose_h2d ? 8'd0 : 8'd1)
  }};

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      epoch_id            <= 64'd0;
      sample_ctr          <= 32'd0;
      record_count        <= 64'd0;
      metadata_bytes      <= 64'd0;
      app_flit_bytes      <= 64'd0;
      stall_cycles        <= 64'd0;
      metadata_drop_count <= 64'd0;
    end else begin
      if (h2d_flit_valid && !h2d_flit_ready) begin
        stall_cycles <= stall_cycles + 64'd1;
      end

      if (any_fire) begin
        app_flit_bytes <= app_flit_bytes + 64'd64;

        if (sample_ctr == SAMPLE_STRIDE - 1) begin
          sample_ctr <= 32'd0;
        end else begin
          sample_ctr <= sample_ctr + 32'd1;
        end

        if (sampled) begin
          record_count   <= record_count + 64'd1;
          metadata_bytes <= metadata_bytes + METADATA_RECORD_BYTES + payload_capture_bytes;
          if (!metadata_ready) begin
            metadata_drop_count <= metadata_drop_count + 64'd1;
          end
        end

        // GEMM-phase epoch policy: compute dispatches and readback starts
        // create phase boundaries. This is the hardware-JIT equivalent of
        // specializing an eBPF-like policy bundle to the endpoint protocol.
        if (choose_h2d && chosen_class == 4'h2 && chosen_token[20]) begin
          epoch_id <= epoch_id + 64'd1;
        end else if (choose_h2d && chosen_class == 4'h1 && epoch_id < 64'd3) begin
          epoch_id <= 64'd3;
        end
      end
    end
  end

  function automatic [63:0] hash_payload(input [FLIT_BITS-1:0] flit);
    integer i;
    reg [63:0] h;
    begin
      h = 64'hcbf29ce484222325;
      for (i = 88; i < 344; i = i + 8) begin
        h = h ^ {{56'd0, flit[i +: 8]}};
        h = h * 64'h00000100000001b3;
      end
      hash_payload = h;
    end
  endfunction

  function automatic [15:0] capture_bytes(input [FLIT_BITS-1:0] flit);
    integer i;
    reg [15:0] changed;
    reg [3:0] cls;
    begin
      cls = flit[7:4];
      changed = 16'd0;
      if (cls == 4'h2 || cls == 4'h3 || cls == 4'h6) begin
        unique case (RECORD_MODE)
          0: capture_bytes = 16'd8;
          1: begin
            for (i = 88; i < 344; i = i + 8) begin
              if (flit[i +: 8] != 8'd0) changed = changed + 16'd1;
            end
            capture_bytes = 16'd8 + (changed << 1);
          end
          default: capture_bytes = 16'd32;
        endcase
      end else begin
        capture_bytes = 16'd0;
      end
    end
  endfunction

endmodule
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::CxlEndpointConfig;

    #[test]
    fn snapshot_hj_pipeline_sv() {
        let cfg = CxlEndpointConfig::slugcxl_4x4();
        let sv = emit(&cfg, &cfg.hardware_jit);
        insta::assert_snapshot!(sv);
    }
}
