//! Emits a top module that inserts the hardware-JIT pipeline around SlugCXL.

use crate::config::CxlEndpointConfig;

pub fn emit(cfg: &CxlEndpointConfig) -> String {
    let token_width = cfg.attached_wrapper.token_width;

    format!(
        r#"// Generated by slugcxl-gen. Do not edit.
// Top wrapper for SlugCXL with endpoint-local Hardware-JIT replay logic.

module slugcxl_4x4_hj_top #(
  parameter integer FLIT_BITS = 512,
  parameter integer TOKEN_WIDTH = {token_width}
) (
  input  wire                     clk,
  input  wire                     rst_n,

  input  wire                     flit_in_valid,
  output wire                     flit_in_ready,
  input  wire [FLIT_BITS-1:0]     flit_in_data,
  output wire                     flit_out_valid,
  input  wire                     flit_out_ready,
  output wire [FLIT_BITS-1:0]     flit_out_data,

  input  wire                     policy_load_begin,
  input  wire                     policy_load_valid,
  output wire                     policy_load_ready,
  input  wire [15:0]              policy_load_index,
  input  wire [127:0]             policy_load_word,
  input  wire                     policy_load_commit,
  input  wire                     policy_load_abort,
  input  wire [255:0]             policy_load_digest,
  input  wire [31:0]              policy_load_instruction_count,
  input  wire [31:0]              policy_load_range_count,
  output wire                     policy_ready,
  output wire [31:0]              policy_error,
  output wire [255:0]             policy_digest,

  output wire                     record_valid,
  input  wire                     record_ready,
  output wire [15:0]              record_length,
  output wire [1023:0]            record_data,

  output wire [63:0]              hj_record_count,
  output wire [63:0]              hj_metadata_bytes,
  output wire [63:0]              hj_app_flit_bytes,
  output wire [63:0]              hj_stall_cycles,
  output wire [63:0]              hj_metadata_drop_count
);

  wire                 w_ep_flit_valid;
  wire                 w_ep_flit_ready;
  wire [FLIT_BITS-1:0] w_ep_flit_data;
  wire                 w_ep_resp_valid;
  wire                 w_ep_resp_ready;
  wire [FLIT_BITS-1:0] w_ep_resp_data;

  slugcxl_hj_pipeline #(
    .FLIT_BITS(FLIT_BITS)
  ) u_hj (
    .clk(clk),
    .rst_n(rst_n),
    .h2d_flit_valid(flit_in_valid),
    .h2d_flit_ready(flit_in_ready),
    .h2d_flit_data(flit_in_data),
    .ep_flit_valid(w_ep_flit_valid),
    .ep_flit_ready(w_ep_flit_ready),
    .ep_flit_data(w_ep_flit_data),
    .ep_resp_valid(w_ep_resp_valid),
    .ep_resp_ready(w_ep_resp_ready),
    .ep_resp_data(w_ep_resp_data),
    .d2h_flit_valid(flit_out_valid),
    .d2h_flit_ready(flit_out_ready),
    .d2h_flit_data(flit_out_data),
    .policy_load_begin(policy_load_begin),
    .policy_load_valid(policy_load_valid),
    .policy_load_ready(policy_load_ready),
    .policy_load_index(policy_load_index),
    .policy_load_word(policy_load_word),
    .policy_load_commit(policy_load_commit),
    .policy_load_abort(policy_load_abort),
    .policy_load_digest(policy_load_digest),
    .policy_load_instruction_count(policy_load_instruction_count),
    .policy_load_range_count(policy_load_range_count),
    .policy_ready(policy_ready),
    .policy_error(policy_error),
    .policy_digest(policy_digest),
    .record_valid(record_valid),
    .record_ready(record_ready),
    .record_length(record_length),
    .record_data(record_data),
    .record_count(hj_record_count),
    .metadata_bytes(hj_metadata_bytes),
    .app_flit_bytes(hj_app_flit_bytes),
    .stall_cycles(hj_stall_cycles),
    .metadata_drop_count(hj_metadata_drop_count)
  );

  slugcxl_4x4_top #(
    .FLIT_BITS(FLIT_BITS),
    .TOKEN_WIDTH(TOKEN_WIDTH)
  ) u_slugcxl (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_valid(w_ep_flit_valid),
    .flit_in_ready(w_ep_flit_ready),
    .flit_in_data(w_ep_flit_data),
    .flit_out_valid(w_ep_resp_valid),
    .flit_out_ready(w_ep_resp_ready),
    .flit_out_data(w_ep_resp_data)
  );

endmodule
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::CxlEndpointConfig;

    #[test]
    fn snapshot_hj_top_sv() {
        let cfg = CxlEndpointConfig::slugcxl_4x4();
        let sv = emit(&cfg);
        insta::assert_snapshot!(sv);
    }
}
