//! Emits a Quartus fit harness with minimal physical IO.

use crate::config::CxlEndpointConfig;

pub fn emit(_cfg: &CxlEndpointConfig) -> String {
    r#"// Generated by slugcxl-gen. Do not edit.
// Quartus fit harness for the hardware-JIT SlugCXL design.
//
// The functional HJ top has wide 512-bit FLIT and 256-bit metadata ports.
// Those are logical fabric interfaces, not package pins. This harness keeps
// that traffic internal for synthesis/resource/overhead builds so Quartus
// does not allocate thousands of IO pads.

module slugcxl_hj_fit_top (
  input  wire clk,
  input  wire rst_n,
  output wire status_led
);

  localparam int FLIT_BITS = 512;

  reg                  flit_in_valid;
  wire                 flit_in_ready;
  reg  [FLIT_BITS-1:0] flit_in_data;
  wire                 flit_out_valid;
  wire [FLIT_BITS-1:0] flit_out_data;
  wire                 metadata_valid;
  wire [255:0]         metadata_data;
  wire [63:0]          hj_record_count;
  wire [63:0]          hj_metadata_bytes;
  wire [63:0]          hj_app_flit_bytes;
  wire [63:0]          hj_stall_cycles;
  wire [63:0]          hj_metadata_drop_count;

  reg [7:0] seq_idx;
  reg       done_q;

  (* preserve *) reg [63:0] observed_record_count;
  (* preserve *) reg [63:0] observed_metadata_bytes;
  (* preserve *) reg [63:0] observed_app_flit_bytes;
  (* preserve *) reg [63:0] observed_stall_cycles;
  (* preserve *) reg [63:0] observed_drop_count;
  (* preserve *) reg [255:0] observed_metadata_last;

  slugcxl_4x4_hj_top #(
    .FLIT_BITS(FLIT_BITS),
    .TOKEN_WIDTH(256)
  ) u_dut (
    .clk(clk),
    .rst_n(rst_n),
    .flit_in_valid(flit_in_valid),
    .flit_in_ready(flit_in_ready),
    .flit_in_data(flit_in_data),
    .flit_out_valid(flit_out_valid),
    .flit_out_ready(1'b1),
    .flit_out_data(flit_out_data),
    .metadata_valid(metadata_valid),
    .metadata_ready(1'b1),
    .metadata_data(metadata_data),
    .hj_record_count(hj_record_count),
    .hj_metadata_bytes(hj_metadata_bytes),
    .hj_app_flit_bytes(hj_app_flit_bytes),
    .hj_stall_cycles(hj_stall_cycles),
    .hj_metadata_drop_count(hj_metadata_drop_count)
  );

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      seq_idx <= 8'd0;
      done_q <= 1'b0;
      flit_in_valid <= 1'b0;
      flit_in_data <= '0;
      observed_record_count <= 64'd0;
      observed_metadata_bytes <= 64'd0;
      observed_app_flit_bytes <= 64'd0;
      observed_stall_cycles <= 64'd0;
      observed_drop_count <= 64'd0;
      observed_metadata_last <= 256'd0;
    end else begin
      observed_record_count <= hj_record_count;
      observed_metadata_bytes <= hj_metadata_bytes;
      observed_app_flit_bytes <= hj_app_flit_bytes;
      observed_stall_cycles <= hj_stall_cycles;
      observed_drop_count <= hj_metadata_drop_count;
      if (metadata_valid) begin
        observed_metadata_last <= metadata_data;
      end

      if (!done_q) begin
        flit_in_valid <= 1'b1;
        flit_in_data <= stimulus_flit(seq_idx);
        if (flit_in_ready) begin
          if (seq_idx == 8'd48) begin
            seq_idx <= seq_idx;
            done_q <= 1'b1;
            flit_in_valid <= 1'b0;
          end else begin
            seq_idx <= seq_idx + 8'd1;
          end
        end
      end else begin
        flit_in_valid <= 1'b0;
      end
    end
  end

  assign status_led =
      done_q
    ^ observed_record_count[0]
    ^ observed_metadata_bytes[0]
    ^ observed_app_flit_bytes[0]
    ^ observed_stall_cycles[0]
    ^ observed_drop_count[0]
    ^ observed_metadata_last[0]
    ^ flit_out_valid
    ^ flit_out_data[0];

  function automatic [FLIT_BITS-1:0] stimulus_flit(input [7:0] idx);
    reg [FLIT_BITS-1:0] f;
    reg [31:0] token;
    reg [63:0] addr;
    reg [15:0] tag;
    begin
      f = '0;
      tag = {8'd0, idx};
      f[23:8] = tag;

      if (idx < 8'd16) begin
        token = make_load_token(1'b0, idx[3:0], idx[7:0] + 8'd1);
        f[7:0] = 8'h20;               // M2SRwD MemWr
        f[87:24] = 64'h0000_0000_0000_2000;
        f[119:88] = token;
      end else if (idx < 8'd32) begin
        token = make_load_token(1'b1, idx[3:0], idx[7:0] + 8'd1);
        f[7:0] = 8'h20;               // M2SRwD MemWr
        f[87:24] = 64'h0000_0000_0000_2000;
        f[119:88] = token;
      end else if (idx == 8'd32) begin
        token = 32'h0010_0000;         // compute_valid
        f[7:0] = 8'h20;               // M2SRwD MemWr
        f[87:24] = 64'h0000_0000_0000_2000;
        f[119:88] = token;
      end else begin
        token = make_read_token(idx - 8'd33);
        addr = 64'h0000_0000_0000_2000 | ({32'd0, token} << 32);
        f[7:0] = 8'h10;               // M2SReq MemRd
        f[87:24] = addr;
      end

      stimulus_flit = f;
    end
  endfunction

  function automatic [31:0] make_load_token(
    input sel,
    input [3:0] cell_idx,
    input [7:0] data
  );
    reg [7:0] row;
    reg [7:0] col;
    reg [7:0] addr;
    begin
      row = {6'd0, cell_idx[3:2]};
      col = {6'd0, cell_idx[1:0]};
      addr = (row << 4) + col;
      make_load_token =
          (32'd1 << 2)
        | ({31'd0, sel} << 3)
        | ({24'd0, addr} << 4)
        | ({24'd0, data} << 12);
    end
  endfunction

  function automatic [31:0] make_read_token(input [7:0] read_idx);
    reg [7:0] row;
    reg [7:0] col;
    reg [7:0] addr;
    begin
      row = {6'd0, read_idx[3:2]};
      col = {6'd0, read_idx[1:0]};
      addr = (row << 4) + col;
      make_read_token = (32'd1 << 21) | ({24'd0, addr} << 22);
    end
  endfunction

endmodule
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::CxlEndpointConfig;

    #[test]
    fn snapshot_fit_top_sv() {
        let cfg = CxlEndpointConfig::slugcxl_4x4();
        let sv = emit(&cfg);
        insta::assert_snapshot!(sv);
    }
}
