//! Emits the runtime-loadable hardware-JIT replay pipeline.

use crate::config::{CxlEndpointConfig, HardwareJitConfig};

pub fn emit(_cfg: &CxlEndpointConfig, _hj: &HardwareJitConfig) -> String {
    r#"// Generated by slugcxl-gen. Do not edit.
// Runtime-loadable SlugArch Hardware-JIT policy and record boundary.
// The 64-byte event encoding is local to SlugArch/Verilator; it is not a
// standards-compliant CXL FLIT.

module slugcxl_hj_pipeline #(
  parameter integer FLIT_BITS = 512
) (
  input  wire                  clk,
  input  wire                  rst_n,

  input  wire                  h2d_flit_valid,
  output wire                  h2d_flit_ready,
  input  wire [FLIT_BITS-1:0]  h2d_flit_data,
  output wire                  ep_flit_valid,
  input  wire                  ep_flit_ready,
  output wire [FLIT_BITS-1:0]  ep_flit_data,

  input  wire                  ep_resp_valid,
  output wire                  ep_resp_ready,
  input  wire [FLIT_BITS-1:0]  ep_resp_data,
  output wire                  d2h_flit_valid,
  input  wire                  d2h_flit_ready,
  output wire [FLIT_BITS-1:0]  d2h_flit_data,

  input  wire                  policy_load_begin,
  input  wire                  policy_load_valid,
  output wire                  policy_load_ready,
  input  wire [15:0]           policy_load_index,
  input  wire [127:0]          policy_load_word,
  input  wire                  policy_load_commit,
  input  wire                  policy_load_abort,
  input  wire [255:0]          policy_load_digest,
  input  wire [31:0]           policy_load_instruction_count,
  input  wire [31:0]           policy_load_range_count,

  output reg                   policy_ready,
  output reg  [31:0]           policy_error,
  output reg  [255:0]          policy_digest,

  output reg                   record_valid,
  input  wire                  record_ready,
  output reg  [15:0]           record_length,
  output reg  [1023:0]         record_data,

  output reg  [63:0]           record_count,
  output reg  [63:0]           metadata_bytes,
  output reg  [63:0]           app_flit_bytes,
  output reg  [63:0]           stall_cycles,
  output reg  [63:0]           metadata_drop_count
);

  localparam [31:0] SLUG_JIT_ERR_STRUCT_SIZE       = 32'd2;
  localparam [31:0] SLUG_JIT_ERR_ABI_VERSION      = 32'd3;
  localparam [31:0] SLUG_JIT_ERR_TOO_MANY_INSTRUCTIONS = 32'd6;
  localparam [31:0] SLUG_JIT_ERR_TOO_MANY_RANGES  = 32'd7;
  localparam [31:0] SLUG_JIT_ERR_INVALID_CONTROL_FLOW = 32'd11;
  localparam [31:0] SLUG_JIT_ERR_DIGEST_MISMATCH  = 32'd13;
  localparam [31:0] SLUG_JIT_ERR_DROP             = 32'd15;
  localparam [31:0] SLUG_JIT_ERR_BACKEND          = 32'd17;

  localparam [31:0] POLICY_MAGIC       = 32'h54494a53; // bytes "SJIT"
  localparam [31:0] POLICY_ABI_VERSION = 32'd1;
  localparam [31:0] EVENT_ABI_VERSION  = 32'd1;
  localparam [31:0] PACKET_ABI_VERSION = 32'd1;
  localparam [31:0] POLICY_IMAGE_BYTES = 32'd640;
  localparam [6:0]  POLICY_IMAGE_WORDS = 7'd40;

  reg [127:0] policy_words_bank0 [0:31];
  reg [127:0] policy_words_bank1 [0:31];
  reg [127:0] range_words_bank0 [0:3];
  reg [127:0] range_words_bank1 [0:3];
  reg         active_bank;
  reg [31:0]  active_instruction_count;
  reg [31:0]  active_range_count;
  reg [31:0]  active_metadata_budget;

  reg         load_in_progress;
  reg         load_bank;
  reg [39:0]  load_seen;
  reg [6:0]   load_word_count;
  reg [31:0]  load_magic;
  reg [31:0]  load_abi_version;
  reg [31:0]  load_event_version;
  reg [31:0]  load_packet_version;
  reg [31:0]  load_instruction_count;
  reg [31:0]  load_range_count;
  reg [31:0]  load_metadata_budget;
  reg [31:0]  load_image_bytes;
  reg [255:0] load_digest_header;

  reg [63:0] sequence_id;
  reg [63:0] epoch_id;
  integer i;

  wire [4:0] policy_slot = policy_load_index[4:0] - 5'd4;
  wire [1:0] range_slot = policy_load_index[1:0];
  assign policy_load_ready =
      load_in_progress
    && (policy_load_index < 16'd40)
    && !load_seen[policy_load_index[5:0]];

  wire record_blocked = policy_ready && record_valid && !record_ready;
  assign ep_flit_valid  = h2d_flit_valid && !record_blocked;
  assign h2d_flit_ready = ep_flit_ready && !record_blocked;
  assign ep_flit_data   = h2d_flit_data;
  assign d2h_flit_valid = ep_resp_valid && !record_blocked;
  assign ep_resp_ready  = d2h_flit_ready && !record_blocked;
  assign d2h_flit_data  = ep_resp_data;

  wire h2d_fire = ep_flit_valid && ep_flit_ready;
  wire d2h_fire = d2h_flit_valid && d2h_flit_ready;
  wire any_fire = h2d_fire || d2h_fire;
  wire dual_fire = h2d_fire && d2h_fire;
  wire choose_h2d = h2d_fire;
  wire [FLIT_BITS-1:0] chosen_flit =
      choose_h2d ? h2d_flit_data : ep_resp_data;

  wire [3:0]  chosen_class       = chosen_flit[7:4];
  wire [3:0]  chosen_opcode      = chosen_flit[3:0];
  wire [15:0] chosen_tag         = chosen_flit[23:8];
  wire [63:0] chosen_address     = chosen_flit[87:24];
  wire [63:0] chosen_event_id    = chosen_flit[407:344];
  wire [63:0] chosen_phase_id    = chosen_flit[471:408];
  wire [31:0] chosen_status      = chosen_flit[503:472];
  wire        chosen_direction   = chosen_flit[511];
  wire [5:0]  chosen_payload_len = chosen_flit[509:504];
  wire [5:0]  bounded_payload_len =
      (chosen_payload_len > 6'd32) ? 6'd32 : chosen_payload_len;
  wire [63:0] chosen_payload_hash =
      hash_payload(chosen_flit, bounded_payload_len);

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      active_bank              <= 1'b0;
      active_instruction_count <= 32'd0;
      active_range_count       <= 32'd0;
      active_metadata_budget   <= 32'd0;
      policy_ready             <= 1'b0;
      policy_error             <= 32'd0;
      policy_digest            <= 256'd0;
      load_in_progress         <= 1'b0;
      load_bank                <= 1'b1;
      load_seen                <= 40'd0;
      load_word_count          <= 7'd0;
      load_magic               <= 32'd0;
      load_abi_version         <= 32'd0;
      load_event_version       <= 32'd0;
      load_packet_version      <= 32'd0;
      load_instruction_count   <= 32'd0;
      load_range_count         <= 32'd0;
      load_metadata_budget     <= 32'd0;
      load_image_bytes         <= 32'd0;
      load_digest_header       <= 256'd0;
      record_valid             <= 1'b0;
      record_length            <= 16'd0;
      record_data              <= 1024'd0;
      record_count             <= 64'd0;
      metadata_bytes           <= 64'd0;
      app_flit_bytes           <= 64'd0;
      stall_cycles             <= 64'd0;
      metadata_drop_count      <= 64'd0;
      sequence_id              <= 64'd0;
      epoch_id                 <= 64'd0;
      for (i = 0; i < 32; i = i + 1) begin
        policy_words_bank0[i] <= 128'd0;
        policy_words_bank1[i] <= 128'd0;
      end
      for (i = 0; i < 4; i = i + 1) begin
        range_words_bank0[i] <= 128'd0;
        range_words_bank1[i] <= 128'd0;
      end
    end else begin
      if (record_valid && record_ready) begin
        record_valid <= 1'b0;
      end
      if (record_valid && !record_ready) begin
        stall_cycles <= stall_cycles + 64'd1;
      end

      if (policy_load_abort) begin
        load_in_progress <= 1'b0;
        load_seen <= 40'd0;
        load_word_count <= 7'd0;
      end else begin
        if (policy_load_begin) begin
          if (load_in_progress) begin
            policy_error <= SLUG_JIT_ERR_BACKEND;
          end else begin
            load_in_progress <= 1'b1;
            load_bank <= ~active_bank;
            load_seen <= 40'd0;
            load_word_count <= 7'd0;
            load_magic <= 32'd0;
            load_abi_version <= 32'd0;
            load_event_version <= 32'd0;
            load_packet_version <= 32'd0;
            load_instruction_count <= 32'd0;
            load_range_count <= 32'd0;
            load_metadata_budget <= 32'd0;
            load_image_bytes <= 32'd0;
            load_digest_header <= 256'd0;
            policy_error <= 32'd0;
            if (active_bank == 1'b0) begin
              for (i = 0; i < 32; i = i + 1)
                policy_words_bank1[i] <= 128'd0;
              for (i = 0; i < 4; i = i + 1)
                range_words_bank1[i] <= 128'd0;
            end else begin
              for (i = 0; i < 32; i = i + 1)
                policy_words_bank0[i] <= 128'd0;
              for (i = 0; i < 4; i = i + 1)
                range_words_bank0[i] <= 128'd0;
            end
          end
        end

        if (policy_load_valid) begin
          if (!load_in_progress) begin
            policy_error <= SLUG_JIT_ERR_BACKEND;
          end else if (policy_load_index >= 16'd40) begin
            policy_error <= SLUG_JIT_ERR_INVALID_CONTROL_FLOW;
          end else if (load_seen[policy_load_index[5:0]]) begin
            policy_error <= SLUG_JIT_ERR_INVALID_CONTROL_FLOW;
          end else begin
            load_seen[policy_load_index[5:0]] <= 1'b1;
            load_word_count <= load_word_count + 7'd1;
            case (policy_load_index)
              16'd0: begin
                load_magic          <= policy_load_word[31:0];
                load_abi_version    <= policy_load_word[63:32];
                load_event_version  <= policy_load_word[95:64];
                load_packet_version <= policy_load_word[127:96];
              end
              16'd1: begin
                load_instruction_count <= policy_load_word[31:0];
                load_range_count       <= policy_load_word[63:32];
                load_metadata_budget   <= policy_load_word[95:64];
                load_image_bytes       <= policy_load_word[127:96];
              end
              16'd2: load_digest_header[127:0] <= policy_load_word;
              16'd3: load_digest_header[255:128] <= policy_load_word;
              default: begin
                if (policy_load_index < 16'd36) begin
                  if (load_bank == 1'b0)
                    policy_words_bank0[policy_slot] <= policy_load_word;
                  else
                    policy_words_bank1[policy_slot] <= policy_load_word;
                end else begin
                  if (load_bank == 1'b0)
                    range_words_bank0[range_slot] <= policy_load_word;
                  else
                    range_words_bank1[range_slot] <= policy_load_word;
                end
              end
            endcase
          end
        end

        if (policy_load_commit) begin
          if (!load_in_progress) begin
            policy_error <= SLUG_JIT_ERR_BACKEND;
          end else if (load_word_count != POLICY_IMAGE_WORDS
                       || load_seen != 40'hffffffffff) begin
            policy_error <= SLUG_JIT_ERR_STRUCT_SIZE;
            load_in_progress <= 1'b0;
          end else if (load_magic != POLICY_MAGIC
                       || load_image_bytes != POLICY_IMAGE_BYTES) begin
            policy_error <= SLUG_JIT_ERR_STRUCT_SIZE;
            load_in_progress <= 1'b0;
          end else if (load_abi_version != POLICY_ABI_VERSION
                       || load_event_version != EVENT_ABI_VERSION
                       || load_packet_version != PACKET_ABI_VERSION) begin
            policy_error <= SLUG_JIT_ERR_ABI_VERSION;
            load_in_progress <= 1'b0;
          end else if (load_instruction_count > 32
                       || load_instruction_count
                          != policy_load_instruction_count) begin
            policy_error <= SLUG_JIT_ERR_TOO_MANY_INSTRUCTIONS;
            load_in_progress <= 1'b0;
          end else if (load_range_count > 4
                       || load_range_count != policy_load_range_count) begin
            policy_error <= SLUG_JIT_ERR_TOO_MANY_RANGES;
            load_in_progress <= 1'b0;
          end else if (load_digest_header != policy_load_digest) begin
            policy_error <= SLUG_JIT_ERR_DIGEST_MISMATCH;
            load_in_progress <= 1'b0;
          end else begin
            active_bank <= load_bank;
            active_instruction_count <= load_instruction_count;
            active_range_count <= load_range_count;
            active_metadata_budget <= load_metadata_budget;
            policy_digest <= load_digest_header;
            policy_ready <= 1'b1;
            policy_error <= 32'd0;
            load_in_progress <= 1'b0;
            epoch_id <= epoch_id + 64'd1;
          end
        end
      end

      if (any_fire) begin
        app_flit_bytes <= app_flit_bytes + (dual_fire ? 64'd128 : 64'd64);
      end
      if (any_fire && policy_ready) begin
        if (!record_valid || record_ready) begin
          sequence_id <= sequence_id + 64'd1;
          epoch_id <= chosen_phase_id;
          record_valid <= 1'b1;
          record_length <= 16'd96;
          record_data <= make_validation_record(
              sequence_id + 64'd1,
              chosen_event_id,
              policy_digest,
              chosen_phase_id,
              chosen_direction,
              chosen_class,
              chosen_opcode,
              chosen_address,
              {{48'd0, chosen_tag}},
              chosen_status,
              bounded_payload_len,
              chosen_payload_hash
          );
          record_count <= record_count + 64'd1;
          metadata_bytes <= metadata_bytes + 64'd8;
        end else begin
          metadata_drop_count <= metadata_drop_count + 64'd1;
          policy_error <= SLUG_JIT_ERR_DROP;
        end
        if (dual_fire) begin
          metadata_drop_count <= metadata_drop_count + 64'd1;
          policy_error <= SLUG_JIT_ERR_DROP;
        end
      end
    end
  end

  function automatic [63:0] hash_payload(
    input [FLIT_BITS-1:0] flit,
    input [5:0] length
  );
    integer byte_index;
    reg [63:0] hash;
    begin
      hash = 64'hcbf29ce484222325;
      for (byte_index = 0; byte_index < 32; byte_index = byte_index + 1) begin
        if (byte_index < length) begin
          hash = hash ^ {{56'd0, flit[88 + byte_index * 8 +: 8]}};
          hash = hash * 64'h00000100000001b3;
        end
      end
      hash_payload = hash;
    end
  endfunction

  function automatic [1023:0] make_validation_record(
    input [63:0] record_sequence,
    input [63:0] event_id,
    input [255:0] digest,
    input [63:0] epoch,
    input direction,
    input [3:0] event_class,
    input [3:0] opcode,
    input [63:0] address,
    input [63:0] tag,
    input [31:0] status,
    input [5:0] payload_length,
    input [63:0] payload_hash
  );
    reg [1023:0] record_bits;
    begin
      record_bits = 1024'd0;
      record_bits[7:0] = 8'd1;
      record_bits[15:8] = 8'd1;
      record_bits[23:16] = 8'd1;
      record_bits[31:24] = 8'd0;
      record_bits[95:32] = record_sequence;
      record_bits[159:96] = event_id;
      record_bits[415:160] = digest;
      record_bits[479:416] = epoch;
      record_bits[487:480] = {{7'd0, direction}};
      record_bits[495:488] = {{4'd0, event_class}};
      record_bits[511:496] = {{12'd0, opcode}};
      record_bits[575:512] = address;
      record_bits[639:576] = tag;
      record_bits[671:640] = status;
      record_bits[679:672] = 8'd0; // validation capture
      record_bits[687:680] = {{2'd0, payload_length}};
      record_bits[695:688] = 8'd8;
      record_bits[703:696] = 8'd0;
      record_bits[767:704] = payload_hash;
      make_validation_record = record_bits;
    end
  endfunction

endmodule
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::CxlEndpointConfig;

    #[test]
    fn snapshot_hj_pipeline_sv() {
        let cfg = CxlEndpointConfig::slugcxl_4x4();
        let sv = emit(&cfg, &cfg.hardware_jit);
        insta::assert_snapshot!(sv);
    }
}
