//! Emits slugcxl_endpoint.sv — the CXL Type-2 endpoint RTL.
//!
//! The endpoint is a single-in-flight state machine:
//!   - Input: 512-bit FLIT on flit_in_data + flit_in_valid handshake.
//!   - Decodes byte 0 for class+opcode, bytes 1-10 for tag+addr, 11-42 for data.
//!   - If class = M2SRwD and addr = dispatch_base: extract 30-bit token from
//!     data[0..4], drive wrapper's cmd_valid + token_in, wait one cycle for
//!     done_valid, build S2MNDR::Cmp, emit on flit_out.
//!   - If class = M2SReq and addr = dispatch_base: drive wrapper with
//!     read-shaped token, wait for done_valid, grab token_out[31:8] as
//!     read_data, build S2MDRS::MemData with data[0..3] = read_data, emit.
//!   - Any other addr: build S2MNDR::DispatchFailed (opcode 0xF), emit.
//!
//! Single-in-flight = flit_in_ready deasserts while a dispatch is pending.

use crate::config::CxlEndpointConfig;

pub fn emit(cfg: &CxlEndpointConfig) -> String {
    let token_width = cfg.attached_wrapper.token_width;
    let dispatch_base = cfg.attached_wrapper.dispatch_base;

    format!(
        r#"// Generated by slugcxl-gen. Do not edit.
// CXL Type-2 endpoint for {ip_name}.
// Protocol subset: .mem (M2S.Req, M2S.RwD, S2M.DRS, S2M.NDR).
// Single-in-flight. No retry buffer, no LTSSM.

module slugcxl_endpoint #(
  parameter integer TOKEN_WIDTH = {token_width},
  parameter integer FLIT_BITS   = 512
) (
  input  wire                     clk,
  input  wire                     rst_n,

  // FLIT in (host -> endpoint)
  input  wire                     flit_in_valid,
  output wire                     flit_in_ready,
  input  wire [FLIT_BITS-1:0]     flit_in_data,

  // FLIT out (endpoint -> host)
  output reg                      flit_out_valid,
  input  wire                     flit_out_ready,
  output reg  [FLIT_BITS-1:0]     flit_out_data,

  // Wrapper interface
  output reg                      cmd_valid,
  input  wire                     cmd_ready,
  output reg  [TOKEN_WIDTH-1:0]   token_in,
  input  wire                     done_valid,
  input  wire [TOKEN_WIDTH-1:0]   token_out
);

  localparam [63:0] DISPATCH_BASE = 64'h{dispatch_base:016x};

  // Incoming FLIT field slices.
  wire [3:0]   in_class   = flit_in_data[7:4];
  wire [3:0]   in_opcode  = flit_in_data[3:0];
  wire [15:0]  in_tag     = flit_in_data[23:8];
  wire [63:0]  in_addr    = flit_in_data[87:24];
  wire [255:0] in_data256 = flit_in_data[343:88];

  // Extracted dispatch token (first 4 bytes of the 32-byte data field).
  wire [31:0]  in_token32 = in_data256[31:0];

  // State machine.
  localparam [2:0] S_IDLE          = 3'd0;
  localparam [2:0] S_DRIVE_CMD     = 3'd1;
  localparam [2:0] S_AWAIT_DONE    = 3'd2;
  localparam [2:0] S_EMIT_CMP      = 3'd3;
  localparam [2:0] S_EMIT_DATA     = 3'd4;
  localparam [2:0] S_EMIT_FAIL     = 3'd5;
  reg [2:0]  state;
  reg [15:0] pend_tag;
  reg        pend_is_read;   // 1 = M2SReq (expect DRS back), 0 = M2SRwD (NDR)
  reg [23:0] pend_read_data;

  assign flit_in_ready = (state == S_IDLE);

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state          <= S_IDLE;
      flit_out_valid <= 1'b0;
      flit_out_data  <= {{FLIT_BITS{{1'b0}}}};
      cmd_valid      <= 1'b0;
      token_in       <= {{TOKEN_WIDTH{{1'b0}}}};
      pend_tag       <= 16'd0;
      pend_is_read   <= 1'b0;
      pend_read_data <= 24'd0;
    end else begin
      case (state)
        S_IDLE: begin
          cmd_valid <= 1'b0;
          // Clear a prior output handshake.
          if (flit_out_valid && flit_out_ready) begin
            flit_out_valid <= 1'b0;
          end
          if (flit_in_valid && flit_in_ready) begin
            pend_tag <= in_tag;
            // Address match.
            if (in_addr == DISPATCH_BASE && in_class == 4'h2) begin
              // M2SRwD -> load/compute dispatch.
              pend_is_read <= 1'b0;
              token_in     <= {{{{(TOKEN_WIDTH-32){{1'b0}}}}, in_token32}};
              state        <= S_DRIVE_CMD;
            end else if (in_addr == DISPATCH_BASE && in_class == 4'h1) begin
              // M2SReq -> read dispatch.
              pend_is_read <= 1'b1;
              token_in     <= {{{{(TOKEN_WIDTH-32){{1'b0}}}}, in_token32}};
              state        <= S_DRIVE_CMD;
            end else begin
              // Unclaimed address.
              state <= S_EMIT_FAIL;
            end
          end
        end

        S_DRIVE_CMD: begin
          cmd_valid <= 1'b1;
          if (cmd_ready) begin
            state <= S_AWAIT_DONE;
          end
        end

        S_AWAIT_DONE: begin
          cmd_valid <= 1'b0;
          if (done_valid) begin
            if (pend_is_read) begin
              pend_read_data <= token_out[31:8];
              state <= S_EMIT_DATA;
            end else begin
              state <= S_EMIT_CMP;
            end
          end
        end

        S_EMIT_CMP: begin
          flit_out_data <= {{FLIT_BITS{{1'b0}}}};
          flit_out_data[7:0]   <= 8'h40;
          flit_out_data[23:8]  <= pend_tag;
          flit_out_valid <= 1'b1;
          if (flit_out_ready) begin
            flit_out_valid <= 1'b0;
            state <= S_IDLE;
          end
        end

        S_EMIT_DATA: begin
          flit_out_data <= {{FLIT_BITS{{1'b0}}}};
          flit_out_data[7:0]    <= 8'h30;
          flit_out_data[23:8]   <= pend_tag;
          flit_out_data[95:88]   <= pend_read_data[7:0];
          flit_out_data[103:96]  <= pend_read_data[15:8];
          flit_out_data[111:104] <= pend_read_data[23:16];
          flit_out_valid <= 1'b1;
          if (flit_out_ready) begin
            flit_out_valid <= 1'b0;
            state <= S_IDLE;
          end
        end

        S_EMIT_FAIL: begin
          flit_out_data <= {{FLIT_BITS{{1'b0}}}};
          flit_out_data[7:0]   <= 8'h4F;
          flit_out_data[23:8]  <= pend_tag;
          flit_out_valid <= 1'b1;
          if (flit_out_ready) begin
            flit_out_valid <= 1'b0;
            state <= S_IDLE;
          end
        end

        default: state <= S_IDLE;
      endcase
    end
  end

endmodule
"#,
        ip_name = cfg.name,
        token_width = token_width,
        dispatch_base = dispatch_base
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snapshot_endpoint_sv() {
        let cfg = CxlEndpointConfig::slugcxl_4x4();
        let sv = emit(&cfg);
        insta::assert_snapshot!(sv);
    }
}
