# Generated by slugcxl-gen.
set project slugcxl_hj_agilex
project_open $project

if {![info exists env(SLUGCXL_AGILEX_DEVICE)]} {
  error "Set SLUGCXL_AGILEX_DEVICE to the exact Quartus device part, e.g. for your Agilex R-Tile board."
}

set_global_assignment -name DEVICE $env(SLUGCXL_AGILEX_DEVICE)
execute_flow -compile
project_close
